import bcrypt from 'bcryptjs';
import { encrypt, encryptSalary } from '../../src/utils/encryption.js';

// ── EMPRESA 1: Empresa Demo Ecuador S.A. (@emplifi.com) ──────────────────────
const EMPLOYEES_EMPRESA_1 = [
    {
        firstName: 'Andrés',
        lastName: 'Morales',
        email: 'andres.morales@emplifi.com',
        identityCard: '1712345678',
        department: 'Tecnología',
        position: 'Desarrollador Senior',
        salary: 2200,
        phone: '0991234567',
        address: 'Av. República del Salvador N36-84, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1990-03-15'),
        hireDate: new Date('2021-06-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '2201234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Valeria',
        lastName: 'Espinoza',
        email: 'valeria.espinoza@emplifi.com',
        identityCard: '1723456789',
        department: 'Recursos Humanos',
        position: 'Coordinadora de RRHH',
        salary: 1800,
        phone: '0982345678',
        address: 'Calle Veintimilla E7-45, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1993-07-22'),
        hireDate: new Date('2020-03-15'),
        bankName: 'Banco Guayaquil',
        accountNumber: '3301234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Diego',
        lastName: 'Vásquez',
        email: 'diego.vasquez@emplifi.com',
        identityCard: '1734567890',
        department: 'Finanzas',
        position: 'Analista Financiero',
        salary: 1950,
        phone: '0973456789',
        address: 'Av. Naciones Unidas E10-44, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1988-11-08'),
        hireDate: new Date('2019-09-01'),
        bankName: 'Produbanco',
        accountNumber: '4401234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Gabriela',
        lastName: 'Torres',
        email: 'gabriela.torres@emplifi.com',
        identityCard: '1745678901',
        department: 'Marketing',
        position: 'Especialista en Marketing Digital',
        salary: 1700,
        phone: '0964567890',
        address: 'Calle Portugal E9-25, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-04-30'),
        hireDate: new Date('2022-01-10'),
        bankName: 'Banco Internacional',
        accountNumber: '5501234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Sebastián',
        lastName: 'Herrera',
        email: 'sebastian.herrera@emplifi.com',
        identityCard: '1756789012',
        department: 'Tecnología',
        position: 'Ingeniero DevOps',
        salary: 2500,
        phone: '0955678901',
        address: 'Av. Amazonas N21-147, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1991-09-14'),
        hireDate: new Date('2021-11-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '6601234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Camila',
        lastName: 'Rodríguez',
        email: 'camila.rodriguez@emplifi.com',
        identityCard: '1767890123',
        department: 'Ventas',
        position: 'Ejecutiva de Ventas',
        salary: 1600,
        phone: '0946789012',
        address: 'Calle Shyris N36-188, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1994-01-25'),
        hireDate: new Date('2022-05-16'),
        bankName: 'Banco del Pacífico',
        accountNumber: '7701234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Mateo',
        lastName: 'Jiménez',
        email: 'mateo.jimenez@emplifi.com',
        identityCard: '1778901234',
        department: 'Operaciones',
        position: 'Coordinador de Operaciones',
        salary: 1850,
        phone: '0937890123',
        address: 'Av. 6 de Diciembre N24-358, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1987-06-03'),
        hireDate: new Date('2018-08-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '8801234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Daniela',
        lastName: 'Salazar',
        email: 'daniela.salazar@emplifi.com',
        identityCard: '1789012345',
        department: 'Legal',
        position: 'Asesora Legal',
        salary: 2100,
        phone: '0928901234',
        address: 'Calle Baquedano E5-29, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1992-12-17'),
        hireDate: new Date('2020-07-01'),
        bankName: 'Produbanco',
        accountNumber: '9901234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Felipe',
        lastName: 'Castillo',
        email: 'felipe.castillo@emplifi.com',
        identityCard: '1790123456',
        department: 'Tecnología',
        position: 'Diseñador UX/UI',
        salary: 1900,
        phone: '0919012345',
        address: 'Av. Colón E4-60, Quito',
        civilStatus: 'Soltero',
        contractType: 'Plazo Fijo',
        birthDate: new Date('1996-08-09'),
        hireDate: new Date('2023-02-01'),
        bankName: 'Banco Internacional',
        accountNumber: '1001234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Kevin',
        lastName: 'Arismendi',
        email: 'kevin.arismendi@emplifi.com',
        identityCard: '1799988877',
        department: 'Tecnología',
        position: 'Junior Developer',
        salary: 950,
        phone: '0999888777',
        address: 'Av. El Inca, Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('2000-05-10'),
        hireDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
        bankName: 'Produbanco',
        accountNumber: '1212121212',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Ricardo',
        lastName: 'Almeida',
        email: 'ricardo.almeida@emplifi.com',
        identityCard: '1791234560',
        department: 'Tecnología',
        position: 'Tech Lead Backend',
        salary: 2600,
        phone: '0998123456',
        address: 'Av. Eloy Alfaro N34-120, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1988-02-14'),
        hireDate: new Date('2020-05-10'),
        bankName: 'Banco Pichincha',
        accountNumber: '1012345678',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Estefanía',
        lastName: 'Moreno',
        email: 'estefania.moreno@emplifi.com',
        identityCard: '1792345671',
        department: 'Tecnología',
        position: 'QA Automation Engineer',
        salary: 1750,
        phone: '0987234567',
        address: 'Calle Guipúzcoa E14-22, Quito',
        civilStatus: 'Soltera',
        contractType: 'Plazo Fijo',
        birthDate: new Date('1994-09-28'),
        hireDate: new Date('2022-08-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '2012345679',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'David',
        lastName: 'Ortega',
        email: 'david.ortega@emplifi.com',
        identityCard: '1793456782',
        department: 'Tecnología',
        position: 'Data Engineer & AI Ops',
        salary: 2150,
        phone: '0976345678',
        address: 'Av. Orellana E8-55, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1992-11-19'),
        hireDate: new Date('2021-04-15'),
        bankName: 'Produbanco',
        accountNumber: '3012345680',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Pablo',
        lastName: 'Guerrero',
        email: 'pablo.guerrero@emplifi.com',
        identityCard: '1794567893',
        department: 'Ventas',
        position: 'Director Comercial',
        salary: 2350,
        phone: '0965456789',
        address: 'Av. 12 de Octubre N26-90, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1986-06-30'),
        hireDate: new Date('2019-10-01'),
        bankName: 'Banco Internacional',
        accountNumber: '4012345681',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Jessica',
        lastName: 'Maldonado',
        email: 'jessica.maldonado@emplifi.com',
        identityCard: '1795678904',
        department: 'Ventas',
        position: 'Account Executive B2B',
        salary: 1550,
        phone: '0954567890',
        address: 'Calle Whymper N30-44, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-03-12'),
        hireDate: new Date('2022-11-10'),
        bankName: 'Banco Pichincha',
        accountNumber: '5012345682',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Esteban',
        lastName: 'Suárez',
        email: 'esteban.suarez@emplifi.com',
        identityCard: '1796789015',
        department: 'Ventas',
        position: 'SDR Prospección Comercial',
        salary: 1100,
        phone: '0943678901',
        address: 'Av. América N31-102, Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1999-10-05'),
        hireDate: new Date('2023-04-01'),
        bankName: 'Banco del Pacífico',
        accountNumber: '6012345683',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Mónica',
        lastName: 'Chávez',
        email: 'monica.chavez@emplifi.com',
        identityCard: '1797890126',
        department: 'Operaciones',
        position: 'Líder de Logística y Procesos',
        salary: 1950,
        phone: '0932789012',
        address: 'Calle Tamayo N24-118, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1989-08-16'),
        hireDate: new Date('2020-09-15'),
        bankName: 'Banco Guayaquil',
        accountNumber: '7012345684',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Rodrigo',
        lastName: 'Zambrano',
        email: 'rodrigo.zambrano@emplifi.com',
        identityCard: '1798901237',
        department: 'Operaciones',
        position: 'Analista de Procesos y Calidad',
        salary: 1450,
        phone: '0921890123',
        address: 'Av. Prensa N45-12, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1996-01-20'),
        hireDate: new Date('2022-03-01'),
        bankName: 'Produbanco',
        accountNumber: '8012345685',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Carolina',
        lastName: 'Vélez',
        email: 'carolina.velez@emplifi.com',
        identityCard: '1799012348',
        department: 'Finanzas',
        position: 'Analista de Tesorería',
        salary: 1650,
        phone: '0910901234',
        address: 'Av. Real Audiencia N55-30, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1993-12-04'),
        hireDate: new Date('2021-07-20'),
        bankName: 'Banco Pichincha',
        accountNumber: '9012345686',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Luis',
        lastName: 'Carrasco',
        email: 'luis.carrasco@emplifi.com',
        identityCard: '1790123459',
        department: 'Marketing',
        position: 'Growth Marketing & Ads Lead',
        salary: 1850,
        phone: '0999012340',
        address: 'Calle Mariscal Foch E4-120, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1991-04-18'),
        hireDate: new Date('2021-02-10'),
        bankName: 'Banco Internacional',
        accountNumber: '1112345687',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Paola',
        lastName: 'Jaramillo',
        email: 'paola.jaramillo@emplifi.com',
        identityCard: '1791234569',
        department: 'Recursos Humanos',
        position: 'Especialista en Cultura y Clima',
        salary: 1600,
        phone: '0988123450',
        address: 'Calle Calama E7-33, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1994-05-24'),
        hireDate: new Date('2022-09-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '2112345688',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Gabriel',
        lastName: 'Enríquez',
        email: 'gabriel.enriquez@emplifi.com',
        identityCard: '1715678902',
        department: 'Tecnología',
        position: 'Especialista en Ciberseguridad & SOC',
        salary: 2750,
        phone: '0981123456',
        address: 'Av. Eloy Alfaro N34-12, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1989-11-04'),
        hireDate: new Date('2021-01-15'),
        bankName: 'Banco Pichincha',
        accountNumber: '2211445566',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Valeria',
        lastName: 'Cárdenas',
        email: 'valeria.cardenas@emplifi.com',
        identityCard: '1726789013',
        department: 'Finanzas',
        position: 'Contadora de Costos & Presupuestos',
        salary: 2100,
        phone: '0992234567',
        address: 'Av. Brasil N42-19, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1991-03-21'),
        hireDate: new Date('2020-08-01'),
        bankName: 'Produbanco',
        accountNumber: '3322556677',
        accountType: 'Ahorros',
        vacationDays: 18,
    },
    {
        firstName: 'Santiago',
        lastName: 'Paredes',
        email: 'santiago.paredes@emplifi.com',
        identityCard: '1737890124',
        department: 'Ventas',
        position: 'Gerente Regional Sierra',
        salary: 2900,
        phone: '0973345678',
        address: 'Av. Interoceánica Km 11, Cumbayá',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1986-07-19'),
        hireDate: new Date('2019-04-10'),
        bankName: 'Banco Guayaquil',
        accountNumber: '4433667788',
        accountType: 'Corriente',
        vacationDays: 20,
    },
    {
        firstName: 'María Elena',
        lastName: 'Noboa',
        email: 'maria.noboa@emplifi.com',
        identityCard: '1748901235',
        department: 'Recursos Humanos',
        position: 'Business Partner de Talento',
        salary: 2250,
        phone: '0984456789',
        address: 'Calle La Niña E4-350, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1992-09-12'),
        hireDate: new Date('2021-06-15'),
        bankName: 'Banco Internacional',
        accountNumber: '5544778899',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Cristian',
        lastName: 'Benalcázar',
        email: 'cristian.benalcazar@emplifi.com',
        identityCard: '1759012346',
        department: 'Operaciones',
        position: 'Supervisor de Planta y Despachos',
        salary: 1650,
        phone: '0965567890',
        address: 'Av. Panamericana Norte Km 8, Carcelén',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1987-12-05'),
        hireDate: new Date('2018-11-20'),
        bankName: 'Banco del Pacífico',
        accountNumber: '6655889900',
        accountType: 'Ahorros',
        vacationDays: 22,
    },
    {
        firstName: 'Ximena',
        lastName: 'Cordero',
        email: 'ximena.cordero@emplifi.com',
        identityCard: '1760123457',
        department: 'Legal',
        position: 'Oficial de Cumplimiento & Riesgos',
        salary: 2600,
        phone: '0976678901',
        address: 'Av. González Suárez N27-40, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1988-04-14'),
        hireDate: new Date('2020-02-15'),
        bankName: 'Produbanco',
        accountNumber: '7766990011',
        accountType: 'Corriente',
        vacationDays: 18,
    },
    {
        firstName: 'Mauricio',
        lastName: 'Villacís',
        email: 'mauricio.villacis@emplifi.com',
        identityCard: '1771234568',
        department: 'Tecnología',
        position: 'Ingeniero de Frontend React Senior',
        salary: 2350,
        phone: '0987789012',
        address: 'Av. Diego de Almagro N31-89, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1993-06-27'),
        hireDate: new Date('2022-03-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '8877001122',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Paulina',
        lastName: 'Alarcón',
        email: 'paulina.alarcon@emplifi.com',
        identityCard: '1782345679',
        department: 'Marketing',
        position: 'Content Manager & Copywriter',
        salary: 1500,
        phone: '0998890123',
        address: 'Calle Guipúzcoa E12-40, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1996-01-30'),
        hireDate: new Date('2023-01-10'),
        bankName: 'Banco Guayaquil',
        accountNumber: '9988112233',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Roberto',
        lastName: 'Cevallos',
        email: 'roberto.cevallos@emplifi.com',
        identityCard: '1793456780',
        department: 'Operaciones',
        position: 'Analista de Inventarios y Bodega',
        salary: 1350,
        phone: '0969901234',
        address: 'Av. Galo Plaza Lasso N60-12, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1994-08-11'),
        hireDate: new Date('2022-07-01'),
        bankName: 'Produbanco',
        accountNumber: '1100223344',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Karina',
        lastName: 'Santamaría',
        email: 'karina.santamaria@emplifi.com',
        identityCard: '1714567891',
        department: 'Ventas',
        position: 'Customer Success Specialist',
        salary: 1450,
        phone: '0971012345',
        address: 'Calle Whymper N29-50, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1997-02-18'),
        hireDate: new Date('2023-05-15'),
        bankName: 'Banco Internacional',
        accountNumber: '2211334455',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Alex',
        lastName: 'Guayasamín',
        email: 'alex.guayasamin@emplifi.com',
        identityCard: '1725678902',
        department: 'Tecnología',
        position: 'DBA & Data Architect',
        salary: 2700,
        phone: '0982123456',
        address: 'Av. Mariana de Jesús E7-40, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1988-10-09'),
        hireDate: new Date('2020-10-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '3322445566',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Andrea',
        lastName: 'Córdova',
        email: 'andrea.cordova@emplifi.com',
        identityCard: '1736789013',
        department: 'Finanzas',
        position: 'Analista de Cartera y Cobranzas',
        salary: 1400,
        phone: '0993234567',
        address: 'Av. América N25-80, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-11-23'),
        hireDate: new Date('2022-10-15'),
        bankName: 'Banco del Pacífico',
        accountNumber: '4433556677',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Marcelo',
        lastName: 'Terán',
        email: 'marcelo.teran@emplifi.com',
        identityCard: '1747890124',
        department: 'Innovación',
        position: 'Product Designer & UX Researcher',
        salary: 2200,
        phone: '0974345678',
        address: 'Calle Isabel La Católica N24-78, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1992-05-14'),
        hireDate: new Date('2021-08-10'),
        bankName: 'Produbanco',
        accountNumber: '5544667788',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Lucía',
        lastName: 'Montesdeoca',
        email: 'lucia.montesdeoca@emplifi.com',
        identityCard: '1758901235',
        department: 'Recursos Humanos',
        position: 'Asistente de Bienestar Social',
        salary: 1200,
        phone: '0985456789',
        address: 'Av. El Inca y 6 de Diciembre, Quito',
        civilStatus: 'Soltera',
        contractType: 'Plazo Fijo',
        birthDate: new Date('1998-07-08'),
        hireDate: new Date('2023-09-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '6655778899',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'José Luis',
        lastName: 'Echeverría',
        email: 'joseluis.echeverria@emplifi.com',
        identityCard: '1769012346',
        department: 'Tecnología',
        position: 'Mobile Engineer Flutter / React Native',
        salary: 2150,
        phone: '0996567890',
        address: 'Calle Tamayo N22-30, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1994-12-16'),
        hireDate: new Date('2022-04-18'),
        bankName: 'Banco Guayaquil',
        accountNumber: '7766889900',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    // Ex-empleados Empresa 1
    {
        firstName: 'Carlos',
        lastName: 'Pérez',
        email: 'carlos.perez.ex@emplifi.com',
        identityCard: '1755544433',
        department: 'Ventas',
        position: 'Ejecutivo de Ventas',
        salary: 1400,
        phone: '0955544433',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1993-01-10'),
        hireDate: new Date('2023-01-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 5, 10),
        isActive: false,
        bankName: 'Banco Pichincha',
        accountNumber: '1111222233',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Mariana',
        lastName: 'Silva',
        email: 'mariana.silva.ex@emplifi.com',
        identityCard: '1744433322',
        department: 'Marketing',
        position: 'Diseñadora Gráfica',
        salary: 1300,
        phone: '0944433322',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-06-12'),
        hireDate: new Date('2022-04-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 4, 15),
        isActive: false,
        bankName: 'Produbanco',
        accountNumber: '2222333344',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Jorge',
        lastName: 'Navarro',
        email: 'jorge.navarro.ex@emplifi.com',
        identityCard: '1733322211',
        department: 'Tecnología',
        position: 'Soporte Técnico',
        salary: 1100,
        phone: '0933322211',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1997-09-05'),
        hireDate: new Date('2023-05-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 3, 20),
        isActive: false,
        bankName: 'Banco Guayaquil',
        accountNumber: '3333444455',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Sofía',
        lastName: 'Cárdenas',
        email: 'sofia.cardenas.ex@emplifi.com',
        identityCard: '1722211100',
        department: 'Operaciones',
        position: 'Asistente de Ops',
        salary: 1000,
        phone: '0922211100',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Temporal',
        birthDate: new Date('1998-03-22'),
        hireDate: new Date('2023-06-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 3, 28),
        isActive: false,
        bankName: 'Produbanco',
        accountNumber: '4444555566',
        accountType: 'Ahorros',
        vacationDays: 0,
    }
];

// ── EMPRESA 2: TechSolutions Cía. Ltda. (@techsolutions.ec) ──────────────────
const EMPLOYEES_EMPRESA_2 = [
    {
        firstName: 'Francisco',
        lastName: 'Jaramillo',
        email: 'francisco.jaramillo@techsolutions.ec',
        identityCard: '1791112233',
        department: 'Desarrollo',
        position: 'Tech Lead Backend',
        salary: 2800,
        phone: '0995551122',
        address: 'Calle La Niña y Eloy Alfaro, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1987-10-10'),
        hireDate: new Date('2020-02-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '9988112233',
        accountType: 'Corriente',
        vacationDays: 18,
    },
    {
        firstName: 'Andrea',
        lastName: 'Benítez',
        email: 'andrea.benitez@techsolutions.ec',
        identityCard: '1792223344',
        department: 'Producto',
        position: 'Product Owner',
        salary: 2400,
        phone: '0984442233',
        address: 'Av. Orellana E4-12, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1991-05-18'),
        hireDate: new Date('2021-04-15'),
        bankName: 'Produbanco',
        accountNumber: '8877223344',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Ricardo',
        lastName: 'Andrade',
        email: 'ricardo.andrade@techsolutions.ec',
        identityCard: '1793334455',
        department: 'Calidad',
        position: 'Lead QA Engineer',
        salary: 2100,
        phone: '0973332211',
        address: 'Av. 12 de Octubre, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1989-12-03'),
        hireDate: new Date('2020-11-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '7766334455',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Lucía',
        lastName: 'Pazmiño',
        email: 'lucia.paz@techsolutions.ec',
        identityCard: '1788877766',
        department: 'Marketing',
        position: 'Marketing Specialist',
        salary: 1750,
        phone: '0988877766',
        address: 'Valle de los Chillos, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1992-10-12'),
        hireDate: new Date('2018-01-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '3434343434',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Isabel',
        lastName: 'Fuentes',
        email: 'isabel.fuentes@techsolutions.ec',
        identityCard: '1766655544',
        department: 'Recursos Humanos',
        position: 'Talent Acquisition Specialist',
        salary: 1850,
        phone: '0966655544',
        address: 'Av. Eloy Alfaro, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1994-05-14'),
        hireDate: new Date('2022-09-15'),
        bankName: 'Produbanco',
        accountNumber: '6677889900',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Miguel',
        lastName: 'Cueva',
        email: 'miguel.cueva@techsolutions.ec',
        identityCard: '1794445566',
        department: 'Desarrollo',
        position: 'Frontend Senior',
        salary: 2300,
        phone: '0951112233',
        address: 'Av. Granda Centeno, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1993-02-24'),
        hireDate: new Date('2021-08-01'),
        bankName: 'Banco Internacional',
        accountNumber: '5544332211',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Cristina',
        lastName: 'Solano',
        email: 'cristina.solano@techsolutions.ec',
        identityCard: '1795556677',
        department: 'Ventas Tech',
        position: 'Account Executive',
        salary: 1950,
        phone: '0942223344',
        address: 'Cumbayá, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-09-08'),
        hireDate: new Date('2022-03-01'),
        bankName: 'Banco del Pacífico',
        accountNumber: '4433221100',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Santiago',
        lastName: 'Vaca',
        email: 'santiago.vaca@techsolutions.ec',
        identityCard: '1796667788',
        department: 'Infraestructura',
        position: 'Cloud Architect',
        salary: 2700,
        phone: '0938889900',
        address: 'Tumbaco, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1986-07-14'),
        hireDate: new Date('2019-11-15'),
        bankName: 'Banco Pichincha',
        accountNumber: '3322110099',
        accountType: 'Corriente',
        vacationDays: 18,
    },
    {
        firstName: 'Roberto',
        lastName: 'Guzmán',
        email: 'roberto.guzman@techsolutions.ec',
        identityCard: '1777766655',
        department: 'Ventas Tech',
        position: 'Gerente Comercial Tech',
        salary: 3200,
        phone: '0977766655',
        address: 'Av. González Suárez, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1984-11-20'),
        hireDate: new Date('2021-03-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '5566778899',
        accountType: 'Corriente',
        vacationDays: 20,
    },
    // Ex-empleados Empresa 2
    {
        firstName: 'Esteban',
        lastName: 'Ríos',
        email: 'esteban.rios.ex@techsolutions.ec',
        identityCard: '1711100099',
        department: 'Ventas Tech',
        position: 'Ejecutivo Senior Ex',
        salary: 1800,
        phone: '0911100099',
        address: 'Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1990-11-30'),
        hireDate: new Date('2021-08-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 2, 12),
        isActive: false,
        bankName: 'Banco Pichincha',
        accountNumber: '5555666677',
        accountType: 'Corriente',
        vacationDays: 0,
    },
    {
        firstName: 'Diana',
        lastName: 'Mejía',
        email: 'diana.mejia.ex@techsolutions.ec',
        identityCard: '1700099988',
        department: 'Calidad',
        position: 'QA Tester Ex',
        salary: 1500,
        phone: '0900099988',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1994-08-18'),
        hireDate: new Date('2022-11-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 2, 25),
        isActive: false,
        bankName: 'Banco Internacional',
        accountNumber: '6666777788',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Víctor',
        lastName: 'Paredes',
        email: 'victor.paredes.ex@techsolutions.ec',
        identityCard: '1777700033',
        department: 'Desarrollo',
        position: 'Junior Frontend Ex',
        salary: 1000,
        phone: '0977700033',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1999-12-05'),
        hireDate: new Date('2023-09-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 28),
        isActive: false,
        bankName: 'Banco Guayaquil',
        accountNumber: '9999000011',
        accountType: 'Ahorros',
        vacationDays: 0,
    }
];

export async function seedUsers(prisma) {
    console.log('[USERS] Configurando exactamente 2 Empresas SaaS con sus equipos completos...');
    const password = await bcrypt.hash('Emplifi2025!', 10);

    // ── 1. EXACTAMENTE 7 TENANTS / EMPRESAS MULTI-SECTOR ─────────────────────
    const TENANTS_TO_SEED = [
        {
            name: 'Empresa Demo Ecuador S.A.',
            slug: 'empresa-demo',
            ruc: '1792345678001',
            plan: 'ENTERPRISE',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 100,
            trialEndsAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'TechSolutions Cía. Ltda.',
            slug: 'tech-solutions',
            ruc: '1798765432001',
            plan: 'GROWTH',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 50,
            trialEndsAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'Innovate Corp S.A.S.',
            slug: 'innovate-corp',
            ruc: '1799988776001',
            plan: 'GROWTH',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 50,
            trialEndsAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'Logística & Distribución Andina S.A.',
            slug: 'logistica-andina',
            ruc: '1791122334001',
            plan: 'ENTERPRISE',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 100,
            trialEndsAt: new Date(Date.now() + 300 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'Clínica Médica Santa Inés S.A.',
            slug: 'clinica-santa-ines',
            ruc: '1792233445001',
            plan: 'ENTERPRISE',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 80,
            trialEndsAt: new Date(Date.now() + 270 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'Comercializadora Retail del Pacífico S.A.',
            slug: 'retail-pacifico',
            ruc: '1793344556001',
            plan: 'GROWTH',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 60,
            trialEndsAt: new Date(Date.now() + 210 * 24 * 60 * 60 * 1000)
        },
        {
            name: 'Manufacturas Industriales Pichincha Cía. Ltda.',
            slug: 'manufacturas-pichincha',
            ruc: '1794455667001',
            plan: 'ESSENTIAL',
            subscriptionStatus: 'ACTIVE',
            maxEmployees: 40,
            trialEndsAt: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000)
        }
    ];

    const createdTenants = {};
    for (const t of TENANTS_TO_SEED) {
        const created = await prisma.tenant.upsert({
            where: { slug: t.slug },
            update: {
                name: t.name,
                ruc: t.ruc,
                plan: t.plan,
                subscriptionStatus: t.subscriptionStatus,
                maxEmployees: t.maxEmployees,
                trialEndsAt: t.trialEndsAt
            },
            create: t
        });
        createdTenants[t.slug] = created;
        console.log(`Tenant Creado/Actualizado: ${created.name} (${created.slug})`);
    }

    const tenant1 = createdTenants['empresa-demo'];
    const tenant2 = createdTenants['tech-solutions'];

    // ── 2. SUPERADMIN GLOBAL ──────────────────────────────────────────────────
    let superAdmin;
    try {
        superAdmin = await prisma.employee.upsert({
            where: { email: 'admin@emplifi.com' },
            update: { password, tenantId: null, role: 'superadmin' },
            create: {
                tenantId: null,
                firstName: 'Jorge',
                lastName: 'Doicela',
                email: 'admin@emplifi.com',
                role: 'superadmin',
                department: 'Administración Global',
                position: 'SuperAdmin SaaS',
                salary: encryptSalary(0),
                password,
                identityCard: '0101010101',
                birthDate: new Date('1980-01-01'),
                hireDate: new Date('2018-01-01'),
                isActive: true,
                address: 'Plataforma Emplifi',
                phone: '0999999999',
                civilStatus: 'Soltero',
                contractType: 'SaaS Owner',
                bankName: encrypt('N/A'),
                accountNumber: encrypt('N/A'),
                accountType: 'N/A',
                vacationDays: 0,
            }
        });
        console.log('SuperAdmin Global: admin@emplifi.com / Emplifi2025!');
    } catch (e) {
        superAdmin = await prisma.employee.findUnique({ where: { email: 'admin@emplifi.com' } });
    }

    // ── 3. EMPRESA 1: Empresa Demo Ecuador S.A. ──────────────────────────────
    const tenant1Employees = [];

    const admin1 = await prisma.employee.upsert({
        where: { email: 'admin.empresa@emplifi.com' },
        update: { password, tenantId: tenant1.id, role: 'admin' },
        create: {
            tenantId: tenant1.id,
            firstName: 'Carlos',
            lastName: 'Mendoza',
            email: 'admin.empresa@emplifi.com',
            role: 'admin',
            department: 'Administración',
            position: 'Gerente General',
            salary: encryptSalary(3500),
            password,
            identityCard: '1711111111',
            birthDate: new Date('1985-04-12'),
            hireDate: new Date('2020-01-01'),
            isActive: true,
            address: 'Av. República del Salvador, Quito',
            phone: '0991111111',
            civilStatus: 'Casado',
            contractType: 'Indefinido',
            bankName: encrypt('Banco Pichincha'),
            accountNumber: encrypt('1111222233'),
            accountType: 'Corriente',
            vacationDays: 15,
        }
    });
    tenant1Employees.push(admin1);

    const accountant1 = await prisma.employee.upsert({
        where: { email: 'contabilidad@emplifi.com' },
        update: { password, tenantId: tenant1.id, role: 'accounting' },
        create: {
            tenantId: tenant1.id,
            firstName: 'Ana',
            lastName: 'Torres',
            email: 'contabilidad@emplifi.com',
            role: 'accounting',
            department: 'Finanzas',
            position: 'Contadora Senior',
            salary: encryptSalary(2500),
            password,
            identityCard: '1799999999',
            birthDate: new Date('1985-05-20'),
            hireDate: new Date('2019-01-15'),
            isActive: true,
            address: 'Av. Gran Colombia, Quito',
            phone: '0988888888',
            civilStatus: 'Casada',
            contractType: 'Indefinido',
            bankName: encrypt('Banco Guayaquil'),
            accountNumber: encrypt('9988776655'),
            accountType: 'Corriente',
            vacationDays: 15,
        }
    });
    tenant1Employees.push(accountant1);

    const entrepreneur1 = await prisma.employee.upsert({
        where: { email: 'emprendedor@emplifi.com' },
        update: { password, tenantId: tenant1.id, role: 'entrepreneur' },
        create: {
            tenantId: tenant1.id,
            firstName: 'Gabriel',
            lastName: 'Silva',
            email: 'emprendedor@emplifi.com',
            role: 'entrepreneur',
            department: 'Innovación',
            position: 'Gestor de Incubadora',
            salary: encryptSalary(2800),
            password,
            identityCard: '1788888888',
            birthDate: new Date('1988-08-08'),
            hireDate: new Date('2023-01-01'),
            isActive: true,
            address: 'Cumbayá, Quito',
            phone: '0977777777',
            civilStatus: 'Soltero',
            contractType: 'Indefinido',
            bankName: encrypt('Banco del Pacífico'),
            accountNumber: encrypt('1122334455'),
            accountType: 'Ahorros',
            vacationDays: 15,
        }
    });
    tenant1Employees.push(entrepreneur1);

    for (const emp of EMPLOYEES_EMPRESA_1) {
        const created = await prisma.employee.upsert({
            where: { email: emp.email },
            update: { password, tenantId: tenant1.id },
            create: {
                tenantId: tenant1.id,
                firstName: emp.firstName,
                lastName: emp.lastName,
                email: emp.email,
                password,
                role: 'employee',
                department: emp.department,
                position: emp.position,
                salary: encryptSalary(emp.salary),
                identityCard: emp.identityCard,
                birthDate: emp.birthDate,
                hireDate: emp.hireDate,
                exitDate: emp.exitDate || null,
                isActive: emp.isActive !== undefined ? emp.isActive : true,
                address: emp.address,
                phone: emp.phone,
                civilStatus: emp.civilStatus,
                contractType: emp.contractType,
                bankName: encrypt(emp.bankName),
                accountNumber: encrypt(emp.accountNumber),
                accountType: emp.accountType,
                vacationDays: emp.vacationDays,
            }
        });
        tenant1Employees.push(created);
    }
    console.log(`Empresa 1 (${tenant1.name}): ${tenant1Employees.length} colaboradores creados.`);

    // ── 4. EMPRESA 2: TechSolutions Cía. Ltda. ─────────────────────────────────
    const tenant2Employees = [];

    const admin2 = await prisma.employee.upsert({
        where: { email: 'admin.tech@techsolutions.ec' },
        update: { password, tenantId: tenant2.id, role: 'admin' },
        create: {
            tenantId: tenant2.id,
            firstName: 'Roberto',
            lastName: 'Guzmán',
            email: 'admin.tech@techsolutions.ec',
            role: 'admin',
            department: 'Administración',
            position: 'Director Ejecutivo',
            salary: encryptSalary(3800),
            password,
            identityCard: '1722222222',
            birthDate: new Date('1984-02-14'),
            hireDate: new Date('2019-06-01'),
            isActive: true,
            address: 'Av. González Suárez, Quito',
            phone: '0992222222',
            civilStatus: 'Casado',
            contractType: 'Indefinido',
            bankName: encrypt('Banco Pichincha'),
            accountNumber: encrypt('2222333344'),
            accountType: 'Corriente',
            vacationDays: 20,
        }
    });
    tenant2Employees.push(admin2);

    const accountant2 = await prisma.employee.upsert({
        where: { email: 'contabilidad.tech@techsolutions.ec' },
        update: { password, tenantId: tenant2.id, role: 'accounting' },
        create: {
            tenantId: tenant2.id,
            firstName: 'Paola',
            lastName: 'Mendoza',
            email: 'contabilidad.tech@techsolutions.ec',
            role: 'accounting',
            department: 'Finanzas',
            position: 'Contadora General Tech',
            salary: encryptSalary(2600),
            password,
            identityCard: '1733333333',
            birthDate: new Date('1989-03-28'),
            hireDate: new Date('2020-08-15'),
            isActive: true,
            address: 'Calle Roca E4-25, Quito',
            phone: '0983333333',
            civilStatus: 'Casada',
            contractType: 'Indefinido',
            bankName: encrypt('Produbanco'),
            accountNumber: encrypt('3333444455'),
            accountType: 'Corriente',
            vacationDays: 15,
        }
    });
    tenant2Employees.push(accountant2);

    const entrepreneur2 = await prisma.employee.upsert({
        where: { email: 'innovacion.tech@techsolutions.ec' },
        update: { password, tenantId: tenant2.id, role: 'entrepreneur' },
        create: {
            tenantId: tenant2.id,
            firstName: 'Patricio',
            lastName: 'Villarreal',
            email: 'innovacion.tech@techsolutions.ec',
            role: 'entrepreneur',
            department: 'Innovación',
            position: 'Líder Lab de Innovación',
            salary: encryptSalary(2900),
            password,
            identityCard: '1744444444',
            birthDate: new Date('1987-11-11'),
            hireDate: new Date('2022-01-10'),
            isActive: true,
            address: 'Tumbaco, Quito',
            phone: '0974444444',
            civilStatus: 'Soltero',
            contractType: 'Indefinido',
            bankName: encrypt('Banco Guayaquil'),
            accountNumber: encrypt('4444555566'),
            accountType: 'Ahorros',
            vacationDays: 15,
        }
    });
    tenant2Employees.push(entrepreneur2);

    for (const emp of EMPLOYEES_EMPRESA_2) {
        const created = await prisma.employee.upsert({
            where: { email: emp.email },
            update: { password, tenantId: tenant2.id },
            create: {
                tenantId: tenant2.id,
                firstName: emp.firstName,
                lastName: emp.lastName,
                email: emp.email,
                password,
                role: 'employee',
                department: emp.department,
                position: emp.position,
                salary: encryptSalary(emp.salary),
                identityCard: emp.identityCard,
                birthDate: emp.birthDate,
                hireDate: emp.hireDate,
                exitDate: emp.exitDate || null,
                isActive: emp.isActive !== undefined ? emp.isActive : true,
                address: emp.address,
                phone: emp.phone,
                civilStatus: emp.civilStatus,
                contractType: emp.contractType,
                bankName: encrypt(emp.bankName),
                accountNumber: encrypt(emp.accountNumber),
                accountType: emp.accountType,
                vacationDays: emp.vacationDays,
            }
        });
        tenant2Employees.push(created);
    }
    console.log(`Empresa 2 (${tenant2.name}): ${tenant2Employees.length} colaboradores creados.`);

    // ── 5. DEMÁS EMPRESAS: Administradores y Equipos Sectoriales ───────────────
    const OTHER_TENANTS_DATA = [
        {
            slug: 'innovate-corp',
            admin: { firstName: 'Verónica', lastName: 'Paredes', email: 'admin.innovate@innovatecorp.ec', department: 'Dirección', position: 'Chief AI Officer', salary: 3400 },
            employees: [
                { firstName: 'Mauricio', lastName: 'Alarcón', email: 'mauricio.alarcon@innovatecorp.ec', identityCard: '1721984756', department: 'Tecnología', position: 'Líder Técnico AI', salary: 2600, phone: '0987123450' },
                { firstName: 'Paulina', lastName: 'Vallejo', email: 'paulina.vallejo@innovatecorp.ec', identityCard: '1718293847', department: 'Tecnología', position: 'Data Scientist Senior', salary: 2400, phone: '0998234561' },
                { firstName: 'Xavier', lastName: 'Cevallos', email: 'xavier.cevallos@innovatecorp.ec', identityCard: '1729384756', department: 'Tecnología', position: 'Ingeniero MLOps', salary: 2100, phone: '0989345672' },
                { firstName: 'Lorena', lastName: 'Benítez', email: 'lorena.benitez@innovatecorp.ec', identityCard: '1710293847', department: 'Ventas', position: 'Directora Comercial', salary: 2100, phone: '0970456783' },
                { firstName: 'Esteban', lastName: 'Guamán', email: 'esteban.guaman@innovatecorp.ec', identityCard: '1723849501', department: 'Ventas', position: 'Account Executive AI', salary: 1650, phone: '0961567894' },
                { firstName: 'Byron', lastName: 'Paredes', email: 'byron.paredes@innovatecorp.ec', identityCard: '1729203148', department: 'Finanzas', position: 'Contador General', salary: 1800, phone: '0997123458' }
            ]
        },
        {
            slug: 'logistica-andina',
            admin: { firstName: 'Fernando', lastName: 'Castro', email: 'admin@logisticaandina.ec', department: 'Gerencia', position: 'Gerente de Operaciones & Logística', salary: 3200 },
            employees: [
                { firstName: 'Hugo', lastName: 'Morán', email: 'hugo.moran@logisticaandina.ec', identityCard: '1713456782', department: 'Operaciones', position: 'Jefe de Flota y Rutas', salary: 1800, phone: '0981239901' },
                { firstName: 'Teresa', lastName: 'Burbano', email: 'teresa.burbano@logisticaandina.ec', identityCard: '1724567893', department: 'Operaciones', position: 'Supervisora de Despachos', salary: 1500, phone: '0992349902' },
                { firstName: 'Gonzalo', lastName: 'Pillajo', email: 'gonzalo.pillajo@logisticaandina.ec', identityCard: '1735678904', department: 'Operaciones', position: 'Coordinador de Almacenes', salary: 1400, phone: '0973459903' },
                { firstName: 'Silvia', lastName: 'Revelo', email: 'silvia.revelo@logisticaandina.ec', identityCard: '1746789015', department: 'Finanzas', position: 'Analista de Costos de Transporte', salary: 1600, phone: '0984569904' },
                { firstName: 'Ramiro', lastName: 'Guanoluisa', email: 'ramiro.guano@logisticaandina.ec', identityCard: '1757890126', department: 'Recursos Humanos', position: 'Generalista de Personal Logístico', salary: 1550, phone: '0965679905' }
            ]
        },
        {
            slug: 'clinica-santa-ines',
            admin: { firstName: 'Dra. Carmen', lastName: 'Salas', email: 'admin@clinicasantaines.ec', department: 'Dirección Médica', position: 'Directora Médica & Administrativa', salary: 3600 },
            employees: [
                { firstName: 'Dr. Marco', lastName: 'Vinueza', email: 'marco.vinueza@clinicasantaines.ec', identityCard: '1719876543', department: 'Médica', position: 'Médico Ocupacional & Auditor', salary: 2800, phone: '0981987654' },
                { firstName: 'Lic. Gladys', lastName: 'Yánez', email: 'gladys.yanez@clinicasantaines.ec', identityCard: '1728765432', department: 'Enfermería', position: 'Jefa de Enfermería', salary: 1750, phone: '0992876543' },
                { firstName: 'Dra. Mónica', lastName: 'Espín', email: 'monica.espin@clinicasantaines.ec', identityCard: '1737654321', department: 'Farmacia', position: 'Química Farmacéutica', salary: 1900, phone: '0973765432' },
                { firstName: 'Lorena', lastName: 'Quishpe', email: 'lorena.quishpe@clinicasantaines.ec', identityCard: '1746543210', department: 'Admisiones', position: 'Coordinadora de Admisiones y Caja', salary: 1250, phone: '0984654321' },
                { firstName: 'Edison', lastName: 'Toapanta', email: 'edison.toapanta@clinicasantaines.ec', identityCard: '1755432109', department: 'Finanzas', position: 'Contador Hospitalario', salary: 1950, phone: '0965543210' }
            ]
        },
        {
            slug: 'retail-pacifico',
            admin: { firstName: 'Guillermo', lastName: 'Lasso V.', email: 'admin@retailpacifico.ec', department: 'Gerencia', position: 'Gerente General Retail', salary: 3300 },
            employees: [
                { firstName: 'Raúl', lastName: 'Campoverde', email: 'raul.campo@retailpacifico.ec', identityCard: '1712233445', department: 'Comercial', position: 'Jefe Nacional de Compras', salary: 2200, phone: '0981223344' },
                { firstName: 'Sonia', lastName: 'Intriago', email: 'sonia.intriago@retailpacifico.ec', identityCard: '1723344556', department: 'Ventas', position: 'Supervisora de Locales y Puntos de Venta', salary: 1600, phone: '0992334455' },
                { firstName: 'Wilmer', lastName: 'Caicedo', email: 'wilmer.caicedo@retailpacifico.ec', identityCard: '1734455667', department: 'Operaciones', position: 'Líder de Merchandising y Góndolas', salary: 1300, phone: '0973445566' },
                { firstName: 'Mayra', lastName: 'Baque', email: 'mayra.baque@retailpacifico.ec', identityCard: '1745566778', department: 'Recursos Humanos', position: 'Analista de Nómina Retail', salary: 1500, phone: '0984556778' }
            ]
        },
        {
            slug: 'manufacturas-pichincha',
            admin: { firstName: 'Ing. Oswaldo', lastName: 'Guevara', email: 'admin@manufacturaspichincha.ec', department: 'Gerencia', position: 'Gerente de Planta y Producción', salary: 3100 },
            employees: [
                { firstName: 'Jaime', lastName: 'Cachipuendo', email: 'jaime.cachi@manufacturaspichincha.ec', identityCard: '1714455661', department: 'Producción', position: 'Supervisor de Turnos Industriales', salary: 1700, phone: '0981445561' },
                { firstName: 'Ángel', lastName: 'Simbaña', email: 'angel.simbana@manufacturaspichincha.ec', identityCard: '1725566772', department: 'Seguridad', position: 'Especialista en Seguridad y Salud Ocupacional', salary: 1850, phone: '0992556772' },
                { firstName: 'Nelson', lastName: 'Farías', email: 'nelson.farias@manufacturaspichincha.ec', identityCard: '1736677883', department: 'Calidad', position: 'Inspector de Control de Calidad', salary: 1400, phone: '0973667883' },
                { firstName: 'Blanca', lastName: 'Molina', email: 'blanca.molina@manufacturaspichincha.ec', identityCard: '1747788994', department: 'Finanzas', position: 'Auxiliar Contable de Planta', salary: 1200, phone: '0984778994' }
            ]
        }
    ];

    for (const tData of OTHER_TENANTS_DATA) {
        const tenant = createdTenants[tData.slug];
        if (!tenant) continue;

        // Admin
        await prisma.employee.upsert({
            where: { email: tData.admin.email },
            update: { password, tenantId: tenant.id, role: 'admin' },
            create: {
                tenantId: tenant.id,
                firstName: tData.admin.firstName,
                lastName: tData.admin.lastName,
                email: tData.admin.email,
                role: 'admin',
                department: tData.admin.department,
                position: tData.admin.position,
                salary: encryptSalary(tData.admin.salary),
                password,
                identityCard: `1799${Math.floor(100000 + Math.random() * 900000)}`,
                birthDate: new Date('1984-06-15'),
                hireDate: new Date('2020-01-10'),
                isActive: true,
                address: 'Quito, Ecuador',
                phone: '0991234500',
                civilStatus: 'Casado',
                contractType: 'Indefinido',
                bankName: encrypt('Banco Pichincha'),
                accountNumber: encrypt('1234567890'),
                accountType: 'Corriente',
                vacationDays: 15,
            }
        });

        // Empleados
        for (const emp of tData.employees) {
            await prisma.employee.upsert({
                where: { email: emp.email },
                update: { password, tenantId: tenant.id },
                create: {
                    tenantId: tenant.id,
                    firstName: emp.firstName,
                    lastName: emp.lastName,
                    email: emp.email,
                    password,
                    role: 'employee',
                    department: emp.department,
                    position: emp.position,
                    salary: encryptSalary(emp.salary),
                    identityCard: emp.identityCard,
                    birthDate: new Date('1992-05-10'),
                    hireDate: new Date('2021-03-01'),
                    isActive: true,
                    address: 'Quito, Ecuador',
                    phone: emp.phone,
                    civilStatus: 'Casado',
                    contractType: 'Indefinido',
                    bankName: encrypt('Banco Guayaquil'),
                    accountNumber: encrypt('9876543210'),
                    accountType: 'Ahorros',
                    vacationDays: 15,
                }
            });
        }
        console.log(`Tenant ${tenant.name} poblado con ${tData.employees.length + 1} colaboradores.`);
    }

    // ── System Settings por Tenant ───────────────────────────────────────────
    await prisma.systemSetting.deleteMany({});
    for (const slug of Object.keys(createdTenants)) {
        const t = createdTenants[slug];
        await prisma.systemSetting.create({
            data: {
                id: `setting-${t.slug}`,
                tenantId: t.id,
                maintenanceMode: false,
                biometricEnabled: true,
                maintenanceMessage: `${t.name} - Operativo`,
            }
        });
    }

    const allUsers = await prisma.employee.findMany();

    return {
        tenant1,
        tenant2,
        superAdmin,
        admin1,
        admin2,
        accountant1,
        accountant2,
        entrepreneur1,
        entrepreneur2,
        tenant1Employees,
        tenant2Employees,
        allEmployees: allUsers,
        admin: admin1,
        employees: tenant1Employees
    };
}

